### ISSUE TITLE
Замечания (дубль два)

### ISSUE THREAD

**Issue by gagarski** [alekseivoroshilov/learningjava#2]
1. Цель данного задания - ознакомить вас с принципами объектно-ориентированного программирования. Вы должны были спроектировать класс `NumberWithDimension`, объект которого представляет число. Операции над ним следовало реализовать в виде методов, то есть, например, сложение будет выглядеть  так:

    Number a = //...;
    Number b = //...;
    Number c = a.add(b);

Ваш подход со статическими методами - это не ООП, а имитация процедурного программирования в объектно-ориентированном языке

2. Сравнивать в тестах строковые предсавления - это плохо. Реализуйте `equals`/`hashCode` у вашего класса и сравнивайте объекты просто с `assertEquals`.

3. Раз уж вы выбрали подход, который поддерживает произвольные размерности (в т. ч. недесятичные), то хорошо бы добавить возможность добавлять новые размерности в некий реестр размерностей. Именно он должен "знать" как переводить минуты в секунды, а не какой-то из методов вашего класса. Этот самый реестр можно реализовать по-разному.
    1. Простой и грязный вариант, оставить его в виде статического поля (но добавить туда коэффициенты для перевода). Добавить статические методы для регистрации новой размерности. Чем плох такой подход, это по сути глобальная переменная, реестр на всех один.
    2. Реализовать класс `MeasurementSystem`, в котором будет храниться этот "реестр", а методы для регистрации будут нестатическими. В `NumberWithDimension` добавить систему мер в качестве поля и передавать в конструкторе. Операции в разных системах не совершать. В `NumberWithDimension` можно добавить метод `newNumber` чтобы более элегантно создавать числа:
```java
Number newNumber(double amount, double subamount, String scaleName) {
    return new Number(this /* текущая система измерений */, numberStr)
}
```

```java
Number a = Number.fromString(measurementSystem, string);
// vs
Number a = measurementSystem.newNumber(string);
```
4. Обрабатывать ошибки следует с помощью исключений. Ваш класс не должен ничего печатать на консоль. Может он будет работать в окружении, где нет консоли.

**Comment by alekseivoroshilov** [comment]
Понял вас! Исправления будут внесены.

**Comment by gagarski** [comment]
Почитайте ещё раз №3, пока вы сделали не совсем то. 

Второе задание вынесите пожалуйста в отдельный репозиторий.

**Comment by alekseivoroshilov** [comment]
Скажите, пожалуйста, что именно вам не понравилось. 

Кроме того, мне не кажется, что все нововведения "совсем не те". Уверен, проблема в чём-то конкретном.

**Comment by alekseivoroshilov** [comment]
Изменения готовы к проверке.

**Comment by gagarski** [comment]
1. Предлагаю всё же ссылку на measurement system хранить в объекте Number. При совершении операций проверять, что они совершаются в рамках одной системы измерений. Сейчас, напрмиер, у вас нельзя прибавить метры к сантиметрам. Но `MeasurementSystem` у вас умеет переводить одно в другое.
2. Под сравнением понималось сравнение на `<` и `>`. Для этого лучше всего реализовать интерфейс `Comparable` (у вас уже есть метод `compareTo` но делает он не совсем то).
3. Не очень хорошо, что объект класса `Number` изменяемый. Например, ваш метод `compareTo` меняет его содержимое и после вызова `compareTo`, может, например, измениться результат `equals`. Предлагаю, во-первых, убрать сеттеры и вместо них добавить аргументы в конструктор. Сделать так, чтобы метод `recalculate` и подобные возвращали новое число, а не изменяли старое.

**Comment by gagarski** [comment]
С `compareTo` всё ещё что-то не то. Почитайте про интерфейс `Comparable`.

**Comment by alekseivoroshilov** [comment]
Вас понял

**Comment by alekseivoroshilov** [comment]
Готовясь к экзамену, вспомнил, что забыл залить исправление.

Я прочитал про этот интерфейс в разных источниках и сделал соответствующие исправления.
Мне казалось, что вы не отвечаете, потому что я всё сделал, но, на самом деле, я отвлёкся в один из дней и закрыл окно проекта, не залив его исправление. Прошу прощения за это.
